import asyncio
import os
import random
from logging import Logger
from typing import Type

from google import genai
from google.genai.types import GenerateContentResponse
from pydantic import BaseModel

from curb_utils.ai_client.config import GeminiOptions


def init_gemini_client(api_key: str | None = None) -> genai.Client:
    """
    Initialize a Gemini Client. If no API key is provided,
    will attempt to load from the environment variable "GEMINI_API_KEY".

    Typically, should be passed to callables querying Gemini as the first argument
    to allow reuse of client across multiple API calls.

    Usage:
        with init_gemini_client(MY_KEY) as client:
            response = func(client, ...)

    Args:
        api_key (str, optional): Valid Google Gemini API Key.

    Returns:
        Gemini API Cient

    Raises:
        RuntimeError: if no API key is provided via args or environment.
    """
    if not api_key:
        try:
            os.environ["GEMINI_API_KEY"]
        except KeyError as exc:
            raise RuntimeError(
                "Must suply a valid Gemini API key either as an arg "
                "or have set GEMINI_API_KEY as an environment variable."
            ) from exc
    client = genai.Client(api_key=api_key)
    return client


async def call_gemini_client_aio(
    client: genai.Client,
    system_instruction: str,
    contents: genai.types.ContentListUnionDict,
    logger: Logger,
    response_schema: Type[BaseModel] | None = None,
    response_mime_type: str = "text/plain",
    model_opts: GeminiOptions | None = None,
) -> GenerateContentResponse:
    """Call the gemini client in asyncio mode

    Args:
        client (genai.Client): Initialized Gemini client
        system_instruction (str): System prompt
        contents (genai.types.ContentListUnionDict): User prompt, possibly including
                                                     images and/or conversation history.
        logger (Logger): Logger
        response_schema (Type[BaseModel] | None, optional): Optional Pydantic model to
            force results to conform to that model.
        response_mime_type (str, optional): Optional mime type, should be
            "application/json" when providing a response schema. Defaults to
            "text/plain".
        model_opts (GeminiOptions | None, optional): Options to control model settings.

    Returns:
        GenerateContentResponse:  Response generated by the AI model.
    """
    # Use the defaults if model_opts are not provided
    if model_opts is None:
        model_opts = GeminiOptions()

    if model_opts.mock_ai:
        # When running a mock AI client, simply pause
        # for a moment and then return an empty content response
        logger.debug("Mocking AI")
        MIN_PAUSE = 1
        MAX_PAUSE = 5
        pause = random.randint(MIN_PAUSE, MAX_PAUSE)
        await asyncio.sleep(pause)  # For async, need to chance to asyncio.sleep(pause)
        return GenerateContentResponse()

    config_gemini_typed = genai.types.GenerateContentConfig(
        system_instruction=system_instruction,
        response_mime_type=response_mime_type,
        temperature=model_opts.temperature,
        response_schema=response_schema,
        thinking_config=genai.types.ThinkingConfig(
            include_thoughts=model_opts.include_thoughts,
            thinking_level=model_opts.thinking_level,
        ),
    )

    return await client.aio.models.generate_content(
        model=model_opts.model,
        contents=contents,
        config=config_gemini_typed,
    )


def call_gemini_client(
    client: genai.Client,
    system_instruction: str,
    contents: genai.types.ContentListUnionDict,
    logger: Logger,
    response_schema: Type[BaseModel] | None = None,
    response_mime_type: str = "text/plain",
    model_opts: GeminiOptions | None = None,
) -> GenerateContentResponse:
    """Call the gemini client in synchronous  mode

    Args:
        client (genai.Client): Initialized Gemini client
        system_instruction (str): System prompt
        contents (genai.types.ContentListUnionDict): User prompt, possibly including
                                                     images and/or conversation history.
        logger (Logger): Logger
        response_schema (Type[BaseModel] | None, optional): Optional Pydantic model to
            force results to conform to that model.
        response_mime_type (str, optional): Optional mime type, should be
            "application/json" when providing a response schema. Defaults to
            "text/plain".
        model_opts (GeminiOptions | None, optional): Options to control model settings.

    Returns:
        GenerateContentResponse:  Response generated by the AI model.
    """

    return asyncio.run(
        call_gemini_client_aio(
            client=client,
            system_instruction=system_instruction,
            contents=contents,
            logger=logger,
            response_schema=response_schema,
            response_mime_type=response_mime_type,
            model_opts=model_opts,
        )
    )
