[project]
name = "smart-prototype"
version = "0.1.0"
description = "A project to organize Boston's Curb data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["data-utils", "curb-utils", "policies-ai"]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.13.3",
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "integration: marks tests that require live Google Cloud resources (slow/expensive)",
]
addopts = "-m 'not integration'"


[tool.uv.sources]
data-utils = {workspace = true}
curb-utils = { workspace = true}
policies-ai = {workspace = true}

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake-8-annotations
    "ANN",
    # flake8-bugbear
    "B",
    # isort
    "I",
]
ignore = [
    # # Type annotations required for self
    "ANN001",
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true