# Configurations for curb geometry creation

# Debug mode (Set this to True for debugging) True does not write to DB.
debug_mode: False

# Input settings
roadway_path: "inputs/Road_Inventory_2024.feather"

# Dictionary of values to keep
include_filters: {'City': [35]}

# Dictionary of values to exclude
exclude_filters: {'F_F_Class': [1, 2], 'Route_System': ['I', 'M', 'R']}

# Process parameters
ft_crs: "epsg:2249"
ft_diff: 0.001

# Geometry adjustment
adjust_geometry: True

# Local output settings
output_path: "outputs"
output_type: "GeoJSON" # "GeoJSON" or "Parquet"
output_crs: "epsg:4326"

# Postgres DB export settings
dbname: "cds"
schema: "staging_next"
job_name: "monorepo blockface rerun"
job_description: "Re-run blockfaces from the combined monorepo again"
