steps:
  blockface_creator: 
    path: "packages/blockface-creator/src/blockface_creator/config.yaml"
    run: False
  curb_segmenter: 
    path: "packages/curb-segmenter/src/curb_segmenter/config.yaml"
    run: False
  sign_reader: 
    path: "packages/sign-reader/src/sign_reader/config.yaml"
    run: False
  policy_applier: 
    path: "packages/policy-applier/src/policy_applier/config.yaml"
    run: True