db_name: "cds"
db_schema: "staging_next"
job_name: "short job name"
job_description: "longer job description"
curb_segmenter_job_id: "c9dc87c2-b318-488c-9c06-ef679923c3ff"
default_parking_anytime: false
write_to_csv: false
csv_file_path: "curb_policy_output.csv"
