# Database settings
db_name: "cds"
db_schema: "staging_demo"
job_name: "short job name"
job_description: "longer job description"

# Source Jobs
source_jobs:
  curb_segmenter: "27c19c05-c820-4799-bb81-c8427b8fef7f"

# Whether to include underlying "Parking Anytime (all users)" policy
default_parking_anytime: false

# Local output for debugging
write_to_csv: false
csv_file_path: "curb_policy_output.csv"
