# ==============================================================================
# Configuration File for Cartegraph Loader
# ==============================================================================
# This YAML file defines all parameters and settings required to run the
# Cartegraph loader workflow. It provides centralized control over data input paths,
# preprocessing options, required parameters, inference thresholds, and output
# specifications.
#
#
# Modify these parameters as needed for different datasets and environments.
# All paths should be absolute or relative to the project root.
# ==============================================================================

job_name: "test-job"
job_description: "this is for testing"
data_source_name: "Cartegraph"

dbname: "cds"
schema: "staging_test"

# Debug mode (Set this to True for debugging) True does not write to DB.
debug_mode: False

signs_path: "data/boston-cartegraph.csv"
input_crs: "EPSG:4326"
neighborhoods_path: "data/boston_neighborhood_boundaries/Boston_Neighborhood_Boundaries.shp"
neightborhoods_crs: "EPSG:4326"

# Columns in the input data
sign_id_col: "oid"
attachment_id_col: "attachment_oid"
uri_col: "attachment_public_url"
notes_col: None
geometry_col: None

output_crs: "EPSG:4326"

# Cartegraph-related Filters
neighborhoods:
  - Charlestown

parking_mutcd_codes:
  - "P-"
  - "MS-"
  - "PB-"
  - "S-"
  - "AC-"
  - "T-"
  - "TS-"
  - "TC-"
  - "R7-107a"
  - "R7-4"
  - "R7-21"

status_filters:
  - "Missing"
  - "Proposed"

grouping_distance_ft: 5
